"""Filtering and ranking of epitope predictions — unified DSL tree.

See :mod:`topiary.ranking.nodes` for the DSL node classes,
:mod:`topiary.ranking.parser` for the string parser, and
:mod:`topiary.ranking.apply` for ``apply_filter`` / ``apply_sort``.
"""

from .nodes import (
    Affinity,
    AggExpr,
    BinOp,
    BoolOp,
    ClipExpr,
    Column,
    Comparison,
    Includes,
    IsIn,
    Const,
    Count,
    DSLNode,
    EvalContext,
    BestAlleleField,
    Field,
    PeptideProperty,
    PeptideView,
    KindAccessor,
    Len,
    LogisticExpr,
    LogisticNormalizedExpr,
    NormExpr,
    Presentation,
    Processing,
    Scope,
    Stability,
    SurvivalExpr,
    UnaryOp,
    class_i,
    class_ii,
    _as_bool_series,
    _as_node,
    _build_kind_aliases,
    _combine_bool,
    _CONTEXT_KEYWORDS,
    _FIELD_ALIASES,
    _fmt_num,
    _gauss_cdf,
    _gauss_cdf_vec,
    _GROUP_KEYS,
    _GROUP_KEYS_VARIANT,
    _iter_known_kinds,
    KIND_ALIASES,
    KIND_MHC_DEPENDENCE,
    MHC_DEPENDENCE_VALUES,
    mhc_dependence,
    _kind_matches,
    _kind_name,
    _kind_short_name,
    _kind_value,
    ALLELE_SET_COLUMN,
    format_allele_set,
    split_allele_set,
    _method_not_found_error,
    _pick_group_keys,
    _resolve_field,
    _resolve_kind,
    _resolve_qualified_kind,
    geomean,
    maximum,
    mean,
    median,
    minimum,
    peptide_view,
    self_nearest,
    self_scope,
    shuffled,
    wt,
)
from .apply import apply_filter, apply_sort, evaluate_scores
from .parser import parse

__all__ = [
    # Core node classes
    "DSLNode",
    "EvalContext",
    "Const",
    "Column",
    "Includes",
    "IsIn",
    "Field",
    "BestAlleleField",
    "PeptideView",
    "PeptideProperty",
    "Len",
    "Count",
    "BinOp",
    "UnaryOp",
    "NormExpr",
    "SurvivalExpr",
    "LogisticExpr",
    "LogisticNormalizedExpr",
    "ClipExpr",
    "AggExpr",
    "Comparison",
    "BoolOp",
    # Accessors and scopes
    "KindAccessor",
    "Scope",
    "Affinity",
    "Presentation",
    "Stability",
    "Processing",
    "class_i",
    "class_ii",
    "wt",
    "shuffled",
    "self_scope",
    "self_nearest",
    # Aggregations
    "mean",
    "geomean",
    "minimum",
    "maximum",
    "median",
    # Public entry points
    "apply_filter",
    "apply_sort",
    "evaluate_scores",
    "parse",
    "format_allele_set",
    "split_allele_set",
    "peptide_view",
    # Kind / field name resolution (public)
    "KIND_ALIASES",
    "KIND_MHC_DEPENDENCE",
    "MHC_DEPENDENCE_VALUES",
    "mhc_dependence",
]
