#!/usr/bin/env python

# Copyright (c) 2014. Mount Sinai School of Medicine
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Script to generate epitope predictions from somatic cancer variants
and (optionally) tumor RNA-seq data.

Example usage:
    topiary \
        -mhc-pan
        --mhc-alleles-file HLA.txt -
        --vcf somatic.vcf
        --rna-gene-fpkm-file genes.fpkm_tracking
        --rna-transcript-fpkm-file isoforms.fpkm_tracking
        --filter-ic50 500
        --filter-percentile 2
        --output results.csv
"""

from topiary import (
    arg_parser,
    mhc_binding_predictor_from_args,
    variant_collection_from_args,
    MutantEpitopePredictor
)
args = arg_parser.parse_args()

def main():
    mhc_model = mhc_binding_predictor_from_args(args)
    predictor = MutantEpitopePredictor(
        mhc_model=mhc_model,
        padding_around_mutation=0)
    variants = variant_collection_from_args(args)
    epitopes = predictor.epitopes_from_variants(variants)
    if args.filter_ic50:
        pass
    if args.filter_percentile:
        pass
    if args.output:
        pass
    print(epitopes)

if __name__ == "__main__":
    main()
